### ISSUE TITLE
Mink Selenium Driver - Exception fillFields() 

### ISSUE THREAD

**Issue by chakibus** [minkphp/MinkSeleniumDriver#57] opened 2015-02-06 17:04 UTC
Hello,

I'm trying to fill a form and I am getting an Exception. 

My scenario: 
```
@javascript @debug
Scenario: Test
    	Given I am on homepage
    	When I fill in "username" with "admin"
    	And I fill in "password" with "admin"
      	And I press "Connexion"
    	Then I should see "Déconnexion"
```
(it's work with goutte)

My composer.json:
```
"require-dev": {
        "matthiasnoback/symfony-config-test": "~0.4",
        "matthiasnoback/symfony-dependency-injection-test": "~0.7",
        "asm89/twig-lint": "@stable",
        "phpunit/phpunit": "~4.2",
        "fabpot/goutte": "~1.0",
        "behat/behat": "~2.4",
        "behat/common-contexts": "*",
        "behat/mink-extension": "~1.2",
        "behat/mink-goutte-driver": "~1.0",
        "behat/mink": "~1.5",
        "behat/mink-browserkit-driver": "~1.1",
        "behat/mink-selenium2-driver": "~1.1",
        "behat/mink-sahi-driver": "~1.1"
    }
```
My behat.yml:
```
default:
    extensions:
        Behat\MinkExtension\Extension:
            files_path: .
            javascript_session: selenium2
            goutte: ~
            selenium2:
                wd_host: http://192.168.5.90:4443/wd/hub
```

I'm running selenium using this command :
java -jar /usr/lib/selenium/selenium-server-standalone-2.44.0.jar

And i'm getting this exception:
```
Exception thrown by (//html/.//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')][(((./@id = 'username' or ./@name = 'username') or ./@id = //label[contains(normalize-space(string(.)), 'username')]/@for) or ./@placeholder = 'username')] | .//label[contains(normalize-space(string(.)), 'username')]//.//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')])[1]
a is undefined
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
```

Also  I'm getting this strack trace:
```
    Given I am on homepage                 # FeatureContext::iAmOnHomepage()
#0 /var/www/canal/vendor/behat/mink/src/Behat/Mink/Element/TraversableElement.php(188): Behat\Mink\Element\NodeElement->setValue('admin')
#1 /var/www/canal/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/MinkContext.php(113): Behat\Mink\Element\TraversableElement->fillField('username', 'admin')
#2 [internal function]: Behat\MinkExtension\Context\MinkContext->fillField('username', 'admin')
#3 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Definition/Annotation/Definition.php(155): call_user_func_array(Array, Array)
#4 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Tester/StepTester.php(157): Behat\Behat\Definition\Annotation\Definition->run(Object(FeatureContext))
#5 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Tester/StepTester.php(126): Behat\Behat\Tester\StepTester->executeStepDefinition(Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\Annotation\When))
#6 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Tester/StepTester.php(95): Behat\Behat\Tester\StepTester->executeStep(Object(Behat\Gherkin\Node\StepNode))
#7 /var/www/canal/vendor/behat/gherkin/src/Behat/Gherkin/Node/AbstractNode.php(42): Behat\Behat\Tester\StepTester->visit(Object(Behat\Gherkin\Node\StepNode))
#8 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Tester/ScenarioTester.php(148): Behat\Gherkin\Node\AbstractNode->accept(Object(Behat\Behat\Tester\StepTester))
#9 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Tester/ScenarioTester.php(87): Behat\Behat\Tester\ScenarioTester->visitStep(Object(Behat\Gherkin\Node\StepNode), Object(Behat\Gherkin\Node\ScenarioNode), Object(FeatureContext), Array, false)
#10 /var/www/canal/vendor/behat/gherkin/src/Behat/Gherkin/Node/AbstractNode.php(42): Behat\Behat\Tester\ScenarioTester->visit(Object(Behat\Gherkin\Node\ScenarioNode))
#11 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Tester/FeatureTester.php(88): Behat\Gherkin\Node\AbstractNode->accept(Object(Behat\Behat\Tester\ScenarioTester))
#12 /var/www/canal/vendor/behat/gherkin/src/Behat/Gherkin/Node/AbstractNode.php(42): Behat\Behat\Tester\FeatureTester->visit(Object(Behat\Gherkin\Node\FeatureNode))
#13 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Console/Command/BehatCommand.php(150): Behat\Gherkin\Node\AbstractNode->accept(Object(Behat\Behat\Tester\FeatureTester))
#14 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Console/Command/BehatCommand.php(128): Behat\Behat\Console\Command\BehatCommand->runFeatures(Object(Behat\Gherkin\Gherkin))
#15 /var/www/canal/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(253): Behat\Behat\Console\Command\BehatCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/canal/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/canal/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Behat\Console\Command\BehatCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/canal/vendor/behat/behat/src/Behat/Behat/Console/BehatApplication.php(68): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/canal/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(126): Behat\Behat\Console\BehatApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/canal/vendor/behat/behat/bin/behat(31): Symfony\Component\Console\Application->run()
#21 {main}%  
```

Thank you for your help

**Comment by aik099** [comment] 2015-02-06 21:24
I interesting but this `a is undefined` text pops up jQuery related issue: http://forum.jquery.com/topic/a-is-undefined .

**Comment by chakibekino** [comment] 2015-02-11 09:47
Thank you for your answer but i don't understand the connection between jQuery and Mink Selenium Driver.

**Comment by aik099** [comment] 2015-02-11 10:19
I guess you might be having JavaScript error caused by jQuery usage on the page you're trying to access through Mink. The Selenium is just logging that error for you.

**Comment by aik099** [comment] 2015-02-11 10:22
Maybe you've enabled strict error reporting in Firefox and that affects your tests somehow, because several jQuery version have strict errors, like undefined variable usage in them.

I suggest trying to use non-minified jQuery version on page you're testing to get more descriptive error in Selenium log.

**Comment by aik099** [comment] 2016-06-20 08:09
Closing due deprecation of the driver.

**Closed by aik099** 2016-06-20 08:09 UTC
